export const infoModulos = [
    {
      id: 0,
      nombre: "Modulo 0",
      docente: "Docente 0",
      apellido_materno: "Flores",
      correo: "alejandra.rodriguez@esam.edu.bo",
    },
    {
      id: 1,
      nombres: "Modulo 1",
      docente: "Docente 1",
      apellido_paterno: "Camacho",
      apellido_materno: "Ferrer",
      correo: "alejandra.camacho@esam.edu.bo",
    },
    {
      id: 2,
      nombres: "Modulo 2",
      docente: "Docente 2",
      apellido_paterno: "Aparicio",
      apellido_materno: "Mogro",
      correo: "maria.aparicio@esam.edu.bo",
    },
    {
      id: 3,
      nombres: "Modulo 3",
      docente: "Docente 3",
      apellido_paterno: "Torrico",
      apellido_materno: "Montaño",
      correo: "camila.torrico@esam.edu.bo",
    },
    {
      id: 4,
      nombres: "Modulo 4",
      docente: "Docente 4",
      apellido_paterno: "Lopez",
      apellido_materno: "Zapata",
      correo: "rosemary.lopez@esam.edu.bo",
    },
    {
      id: 5,
      nombres: "Modulo 5",
      docente: "Docente 5",
      apellido_paterno: "Maire",
      apellido_materno: "Alcocer",
      correo: "maria.maire@esam.edu.bo",
    },
    {
      id: 6,
      nombres: "Modulo 6",
      docente: "Docente 6",
      apellido_paterno: "Vega",
      apellido_materno: "Rojas",
      correo: "anahi.vega@esam.edu.bo",
    },
    {
        id: 7,
        nombres: "Modulo 7",
        docente: "Docente 7",
        apellido_paterno: "Vega",
        apellido_materno: "Rojas",
        correo: "anahi.vega@esam.edu.bo",
      },
  ];
  